# Generated by Django 5.2 on 2025-04-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_blog_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tags',
        ),
    ]
